import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`w-full h-full  font-[400] border-2 `}
//       >
//         <div className='w-full border-2 bg-green-500 mx-auto'>
//           {children}
//         </div>
        
//       </body>
//     </html>
//   );
// }
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen font-[400]">
        <div className={`min-h-screen flex flex-col bg-white ${geistSans.className}`}>
          {children}
        </div>
      </body>
    </html>
  );
}
